#!/usr/bin/env bash
# Regenerate tests/fixtures/rls-schema.sql from the live catalogue (read-only).
set -euo pipefail
cd "$(dirname "$0")/.."
{
cat <<'HDR'
-- GENERATED by scripts/dump-rls-fixture.sh — do not edit by hand.
-- Structural mirror of the live access-control layer: enums, the columns of the
-- tables under test, the app_private/public authorisation helpers, RLS enablement
-- and every SELECT-capable policy. Loaded into an in-process PGlite database by
-- tests/rls-isolation.test.ts and seeded with SYNTHETIC data only.
create role anon;
create role authenticated;
create role service_role;
create schema if not exists auth;
create schema if not exists app_private;
create table auth.users(id uuid primary key, email text);
create or replace function auth.uid() returns uuid language sql stable as $fn$ select nullif(current_setting('request.jwt.claims', true)::json->>'sub','')::uuid $fn$;
create or replace function auth.role() returns text language sql stable as $fn$ select current_setting('request.jwt.claims', true)::json->>'role' $fn$;
create or replace function auth.jwt() returns jsonb language sql stable as $fn$ select coalesce(current_setting('request.jwt.claims', true),'{}')::jsonb $fn$;
grant usage on schema public, app_private, auth to authenticated;
set check_function_bodies = off;
HDR
psql -q -t -A -f scripts/dump-rls-fixture.sql
} > tests/fixtures/rls-schema.sql
echo "wrote tests/fixtures/rls-schema.sql"
