#!/usr/bin/env bash
# Regenerate tests/fixtures/rls-schema.sql from the live catalogue (read-only).
#
# The header below is the Supabase auth mirror: the parts of the live platform
# that RLS policies and definer functions depend on but that are not in the
# `public` schema. It must stay faithful — every difference is a test result the
# live system would not give.
set -euo pipefail
cd "$(dirname "$0")/.."
{
cat <<'HDR'
-- GENERATED by scripts/dump-rls-fixture.sh — do not edit by hand.
--
-- Structural mirror of the live access-control layer, loaded into an in-process
-- PGlite database by tests/access-matrix.test.ts and tests/rls-isolation.test.ts
-- and seeded with SYNTHETIC data only. It never touches the real database.
--
-- Mirror faithfulness (see the plan, Phase 2 section 1):
--   * auth.uid() / auth.role() / auth.jwt() read request.jwt.claims, as live.
--   * auth.users and auth.mfa_factors exist with the columns the policies and
--     the definer functions read.
--   * roles anon / authenticated / service_role exist, and the dump below
--     reproduces the live TABLE and COLUMN grants for each of them.
--   * definer functions are owned by the bootstrap superuser, which has
--     rolbypassrls — the same situation as live, where every public object is
--     owned by `postgres` (rolbypassrls). Recorded in the spec, section 12.
create role anon;
create role authenticated;
create role service_role bypassrls;
create schema if not exists auth;
create schema if not exists app_private;

create table auth.users(
  id uuid primary key,
  email text,
  raw_user_meta_data jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  deleted_at timestamptz
);
create table auth.mfa_factors(
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  status text,
  factor_type text default 'totp',
  created_at timestamptz default now()
);

create or replace function auth.uid() returns uuid language sql stable as $fn$
  select nullif(current_setting('request.jwt.claims', true)::json->>'sub','')::uuid $fn$;
create or replace function auth.role() returns text language sql stable as $fn$
  select current_setting('request.jwt.claims', true)::json->>'role' $fn$;
create or replace function auth.jwt() returns jsonb language sql stable as $fn$
  select coalesce(current_setting('request.jwt.claims', true),'{}')::jsonb $fn$;

grant usage on schema public, app_private, auth to anon, authenticated, service_role;
grant select on auth.users, auth.mfa_factors to service_role;
set check_function_bodies = off;
HDR
psql -q -t -A -f scripts/dump-rls-fixture.sql
} > tests/fixtures/rls-schema.sql
echo "wrote tests/fixtures/rls-schema.sql"
grep -c 'create policy' tests/fixtures/rls-schema.sql | sed 's/^/policies: /'
grep 'catalogue-fingerprint' tests/fixtures/rls-schema.sql
