import { createClient } from "@supabase/supabase-js";
import { writeFileSync } from "fs";
const url=process.env.SUPABASE_URL!,anon=process.env.SUPABASE_PUBLISHABLE_KEY!,svc=process.env.SUPABASE_SERVICE_ROLE_KEY!;
const admin=createClient(url,svc,{auth:{persistSession:false}});
const {decryptToken}=await import("../src/lib/crypto.server");
const {totpCode}=await import("../src/lib/totp.server");
const {data:a}:any=await admin.from("security_test_accounts" as any).select("user_id,email,password_enc,totp_secret_enc").eq("label","staff").maybeSingle();
await admin.auth.admin.updateUserById(a.user_id,{ban_duration:"none"});
const c=createClient(url,anon,{auth:{persistSession:false}});
await c.auth.signInWithPassword({email:a.email,password:decryptToken(a.password_enc)});
const f=await c.auth.mfa.listFactors();const fid=f.data!.totp[0].id;
const ch=await c.auth.mfa.challenge({factorId:fid});
const v=await c.auth.mfa.verify({factorId:fid,challengeId:ch.data!.id,code:totpCode(decryptToken(a.totp_secret_enc))});
const s=v.data!;
const sid=JSON.parse(Buffer.from(s.access_token.split(".")[1],"base64url").toString()).session_id;
await admin.from("session_activity" as any).delete().eq("session_id",sid);
writeFileSync("/tmp/browser/idle/session.json",JSON.stringify({currentSession:s,expiresAt:s.expires_at}));
writeFileSync("/tmp/browser/idle/sid.txt",sid);
console.log("session opened, activity row cleared. session_id:",sid);
