import { createClient } from "@supabase/supabase-js";
const url = process.env.SUPABASE_URL!, anon = process.env.SUPABASE_PUBLISHABLE_KEY!, svc = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const admin = createClient(url, svc, { auth: { persistSession: false } });
const { decryptToken } = await import("../src/lib/crypto.server");
const { totpCode } = await import("../src/lib/totp.server");
const { data: acct } = await admin.from("security_test_accounts" as any).select("user_id,email,password_enc,totp_secret_enc").eq("label","staff").maybeSingle();
const a: any = acct;
const email = a.email, password = decryptToken(a.password_enc), secret = decryptToken(a.totp_secret_enc);
await admin.auth.admin.updateUserById(a.user_id, { ban_duration: "none" });
const c = createClient(url, anon, { auth: { persistSession: false } });
const si = await c.auth.signInWithPassword({ email, password });
if (si.error) throw si.error;
const f = await c.auth.mfa.listFactors();
const fid = f.data?.totp?.[0]?.id!;
const ch = await c.auth.mfa.challenge({ factorId: fid });
const v = await c.auth.mfa.verify({ factorId: fid, challengeId: ch.data!.id, code: totpCode(secret) });
if (v.error) throw v.error;
const tok = v.data.access_token;
const claims = JSON.parse(Buffer.from(tok.split(".")[1], "base64url").toString());
console.log("POST-MFA CLAIM KEYS:", Object.keys(claims).sort().join(","));
console.log("aal:", claims.aal, "session_id:", claims.session_id);
const u = createClient(url, anon, { global: { headers: { Authorization: `Bearer ${tok}`, apikey: anon } }, auth: { persistSession: false } });
console.log("session_is_active:", JSON.stringify(await u.rpc("session_is_active" as any)));
console.log("touch:", JSON.stringify(await u.rpc("touch_session_activity" as any)));
const { data: row } = await admin.from("session_activity" as any).select("*").eq("session_id", claims.session_id).maybeSingle();
console.log("activity row:", JSON.stringify(row));
const { data: s } = await admin.rpc("noop" as any).then(()=>({data:null}), ()=>({data:null}));
await c.auth.signOut();
await admin.auth.admin.updateUserById(a.user_id, { ban_duration: "876000h" });
console.log("re-banned");
