-- GENERATED by scripts/dump-rls-fixture.sql — do not edit by hand.
-- Structural mirror of the live access-control layer: enums, the columns of the
-- tables under test, the app_private/public authorisation helpers, RLS enablement
-- and every SELECT-capable policy. Loaded into an in-process PGlite database by
-- tests/rls-isolation.test.ts and seeded with SYNTHETIC data only.
create role anon;
create role authenticated;
create role service_role;
create schema if not exists auth;
create schema if not exists app_private;
create table auth.users(id uuid primary key, email text);
create or replace function auth.uid() returns uuid language sql stable as $fn$ select nullif(current_setting('request.jwt.claims', true)::json->>'sub','')::uuid $fn$;
create or replace function auth.role() returns text language sql stable as $fn$ select current_setting('request.jwt.claims', true)::json->>'role' $fn$;
create or replace function auth.jwt() returns jsonb language sql stable as $fn$ select coalesce(current_setting('request.jwt.claims', true),'{}')::jsonb $fn$;
grant usage on schema public, app_private, auth to authenticated;
Output format is unaligned.
create type public.app_role as enum ('advisor', 'client_viewer', 'super_admin', 'firm_owner', 'firm_staff');
create type public.dashboard_tier as enum ('basic', 'advisory', 'investigate', 'multi_company');
create type public.report_basis as enum ('accrual', 'cash');
create type public.subscription_tier as enum ('starter', 'growth', 'scale', 'firm', 'legacy', 'free');
create type public.subscription_status as enum ('trialing', 'active', 'past_due', 'canceled', 'incomplete', 'incomplete_expired', 'unpaid');
create type public.firm_member_role as enum ('owner', 'staff');
create type public.client_subscription_type as enum ('paid', 'free_forever', 'trial');
create type public.client_subscription_status as enum ('active', 'trialing', 'past_due', 'cancelled', 'free_forever');
create table public.reconciliation_snapshots (id uuid, client_id uuid, tenant_id text, report_key text, as_at date, payload jsonb, complete boolean, generated_by uuid, generated_at timestamp with time zone);
create table public.client_access (id uuid, client_id uuid, user_id uuid, tier text, created_at timestamp with time zone, updated_at timestamp with time zone);
create table public.client_xero_orgs (id uuid, client_id uuid, xero_connection_id uuid, created_at timestamp with time zone);
create table public.xero_connections (id uuid, user_id uuid, tenant_id text, tenant_name text, tenant_type text, expires_at timestamp with time zone, scopes text, created_at timestamp with time zone, updated_at timestamp with time zone, firm_id uuid, access_token_enc bytea, refresh_token_enc bytea, enc_version smallint, status text, disconnected_at timestamp with time zone, base_currency text);
create table public.user_roles (id uuid, user_id uuid, role app_role, created_at timestamp with time zone);
create table public.consolidation_groups (id uuid, firm_id uuid, name text, created_by uuid, created_at timestamp with time zone, updated_at timestamp with time zone);
create table public.client_notes (id uuid, client_id uuid, author_id uuid, body text, created_at timestamp with time zone, updated_at timestamp with time zone, include_in_report boolean);
create table public.clients (id uuid, name text, owner_user_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone, notes text, report_basis report_basis, firm_id uuid, cost_classification_enabled boolean, basis_overrides jsonb, max_xero_orgs integer, dashboard_widgets text[], consolidation_mode text, consolidation_org_ids uuid[], logo_path text);
create table public.unreconciled_lines (id uuid, upload_id uuid, client_id uuid, account_name text, account_number text, row_index integer, txn_date date, payee text, reference text, spent numeric(14,2), received numeric(14,2), tax text, source_comment text, client_comment text, created_at timestamp with time zone, updated_at timestamp with time zone);
create table public.report_cache (id uuid, user_id uuid, tenant_id text, report_key text, params_hash text, payload jsonb, fetched_at timestamp with time zone);
create table public.loan_consolidation_snapshots (id uuid, group_id uuid, as_at date, label text, payload jsonb, generated_by uuid, generated_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone);
create table public.client_reports (id uuid, client_id uuid, firm_id uuid, tenant_id text, report_key text, period_end date, title text, payload jsonb, payload_version integer, pdf_path text, status text, version integer, complete boolean, generated_by uuid, generated_at timestamp with time zone, finalised_at timestamp with time zone, sent_at timestamp with time zone, sent_to text[]);
create table public.firm_support_access (firm_id uuid, granted boolean, granted_by uuid, granted_at timestamp with time zone, revoked_at timestamp with time zone, note text, created_at timestamp with time zone, updated_at timestamp with time zone, id uuid, grantee_user_id uuid, expires_at timestamp with time zone, requested_by uuid, reason text);
create table public.xero_oauth_states (state text, user_id uuid, code_verifier text, created_at timestamp with time zone, return_origin text, expires_at timestamp with time zone, client_id uuid, flow text, known_tenant_ids text[], pending_tenant_ids text[], completed_at timestamp with time zone, firm_id uuid);
create table public.firm_members (id uuid, firm_id uuid, user_id uuid, role firm_member_role, created_at timestamp with time zone, updated_at timestamp with time zone, status text);
create table public.xero_snapshots (id uuid, client_id uuid, firm_id uuid, tenant_id text, report_key text, params_hash text, params jsonb, source_endpoint text, payload jsonb, payload_version integer, as_at timestamp with time zone, fetched_at timestamp with time zone, complete boolean, run_id uuid, created_at timestamp with time zone, updated_at timestamp with time zone);
create table public.firms (id uuid, name text, owner_user_id uuid, is_always_free boolean, created_at timestamp with time zone, updated_at timestamp with time zone, default_widgets text[], logo_path text);
create table public.client_subscriptions (id uuid, client_id uuid, stripe_customer_id text, stripe_subscription_id text, plan_name text, subscription_type client_subscription_type, status client_subscription_status, current_period_end timestamp with time zone, trial_end timestamp with time zone, past_due_since timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, dashboard_tier dashboard_tier, promotion_code text, coupon_id text, comp_reason text, comped_by uuid, comped_at timestamp with time zone);
create table public.audit_log (id uuid, actor_user_id uuid, firm_id uuid, action text, target_type text, target_id text, ip text, user_agent text, meta jsonb, at timestamp with time zone);
create table public.subscriptions (id uuid, firm_id uuid, stripe_customer_id text, stripe_subscription_id text, tier text, status subscription_status, trial_ends_at timestamp with time zone, current_period_end timestamp with time zone, cancel_at_period_end boolean, created_at timestamp with time zone, updated_at timestamp with time zone, client_limit_override integer, consolidation_enabled boolean, wip_enabled boolean);
CREATE OR REPLACE FUNCTION public.firm_access_path(_user_id uuid, _firm_id uuid)
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select case
    when _user_id is null or _firm_id is null then 'none'
    when app_private.has_firm_access(_user_id, _firm_id) then 'member'
    when app_private.platform_staff_can_access_firm(_user_id, _firm_id) then 'support_grant'
    else 'none'
  end
$function$
;
CREATE OR REPLACE FUNCTION app_private.is_firm_owner(_user_id uuid, _firm_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.firm_members
    where user_id = _user_id and firm_id = _firm_id
      and role = 'owner' and status = 'active'
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.get_user_firm_id(_user_id uuid)
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select firm_id from public.firm_members
  where user_id = _user_id and status = 'active'
  order by created_at
  limit 1
$function$
;
CREATE OR REPLACE FUNCTION app_private.has_client_access(_user_id uuid, _client_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ SELECT EXISTS (SELECT 1 FROM public.client_access WHERE user_id = _user_id AND client_id = _client_id) $function$
;
CREATE OR REPLACE FUNCTION app_private.get_user_tier(_user_id uuid, _tenant_id text)
 RETURNS dashboard_tier
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT ca.tier
  FROM public.client_access ca
  JOIN public.client_xero_orgs cxo ON cxo.client_id = ca.client_id
  JOIN public.xero_connections xc ON xc.id = cxo.xero_connection_id
  WHERE ca.user_id = _user_id AND xc.tenant_id = _tenant_id
  ORDER BY CASE ca.tier WHEN 'investigate' THEN 3 WHEN 'advisory' THEN 2 ELSE 1 END DESC
  LIMIT 1
$function$
;
CREATE OR REPLACE FUNCTION app_private.get_tier_widgets(_client_id uuid, _tier dashboard_tier)
 RETURNS text[]
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT COALESCE(
    (SELECT widgets FROM public.tier_widget_config WHERE client_id = _client_id AND tier = _tier),
    (SELECT widgets FROM public.tier_widget_config WHERE client_id IS NULL AND tier = _tier),
    ARRAY[]::text[]
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.is_advisor(_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = 'advisor') $function$
;
CREATE OR REPLACE FUNCTION app_private.is_super_admin(_user_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = 'super_admin') $function$
;
CREATE OR REPLACE FUNCTION app_private.has_role(_user_id uuid, _role app_role)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $function$
;
CREATE OR REPLACE FUNCTION app_private.has_firm_access(_user_id uuid, _firm_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.firm_members
    where user_id = _user_id and firm_id = _firm_id and status = 'active'
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.user_can_manage_client(_user_id uuid, _client_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.clients c
    WHERE c.id = _client_id
      AND (
        c.owner_user_id = _user_id
        OR (c.firm_id IS NOT NULL AND app_private.has_firm_access(_user_id, c.firm_id))
        OR (
          app_private.is_super_admin(_user_id)
          AND app_private.platform_staff_can_access_firm(_user_id, c.firm_id)
        )
      )
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.shares_firm_with(_viewer uuid, _subject uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.firm_members vm
    JOIN public.firm_members sm ON sm.firm_id = vm.firm_id
    WHERE vm.user_id = _viewer AND sm.user_id = _subject
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.move_xero_file_to_client(_connection_id uuid, _target_client_id uuid, _actor_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO 'public', 'app_private'
AS $function$
DECLARE
  v_source_client_id uuid;
  v_source_firm_id uuid;
  v_target_firm_id uuid;
BEGIN
  IF NOT app_private.user_can_manage_client(_actor_user_id, _target_client_id) THEN RAISE EXCEPTION 'You cannot manage the target client subscription'; END IF;
  SELECT cxo.client_id, c.firm_id INTO v_source_client_id, v_source_firm_id
  FROM public.client_xero_orgs cxo JOIN public.clients c ON c.id = cxo.client_id
  WHERE cxo.xero_connection_id = _connection_id FOR UPDATE OF cxo;
  SELECT firm_id INTO v_target_firm_id FROM public.clients WHERE id = _target_client_id;
  IF v_source_client_id IS NULL THEN RAISE EXCEPTION 'That Xero file is no longer linked to another subscription'; END IF;
  IF v_source_client_id = _target_client_id THEN RAISE EXCEPTION 'That Xero file is already linked to this subscription'; END IF;
  IF v_source_firm_id IS DISTINCT FROM v_target_firm_id AND NOT app_private.is_super_admin(_actor_user_id) THEN RAISE EXCEPTION 'Only a platform admin can move a Xero file between organisations'; END IF;
  IF NOT app_private.is_super_admin(_actor_user_id) AND NOT app_private.user_can_manage_client(_actor_user_id, v_source_client_id) THEN RAISE EXCEPTION 'You cannot manage the subscription that currently holds this Xero file'; END IF;
  DELETE FROM public.client_xero_orgs WHERE xero_connection_id = _connection_id;
  INSERT INTO public.client_xero_orgs (client_id, xero_connection_id) VALUES (_target_client_id, _connection_id);
  UPDATE public.xero_connections SET firm_id = v_target_firm_id WHERE id = _connection_id;
END;
$function$
;
CREATE OR REPLACE FUNCTION app_private.platform_staff_can_access_firm(_user_id uuid, _firm_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select _firm_id is not null
     and app_private.is_super_admin(_user_id)
     and app_private.firm_support_access_active(_user_id, _firm_id)
$function$
;
CREATE OR REPLACE FUNCTION app_private.firm_support_access_active(_user_id uuid, _firm_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.firm_support_access fsa
    where fsa.firm_id = _firm_id
      and fsa.grantee_user_id = _user_id
      and fsa.granted = true
      and fsa.revoked_at is null
      and fsa.expires_at > now()
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.firm_ids_for_tenant(_tenant_id text)
 RETURNS SETOF uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select xc.firm_id from public.xero_connections xc
   where xc.tenant_id = _tenant_id and xc.firm_id is not null
  union
  select c.firm_id
    from public.client_xero_orgs cxo
    join public.clients c on c.id = cxo.client_id
    join public.xero_connections xc2 on xc2.id = cxo.xero_connection_id
   where xc2.tenant_id = _tenant_id and c.firm_id is not null
$function$
;
CREATE OR REPLACE FUNCTION app_private.user_can_access_tenant(_user_id uuid, _tenant_id text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from app_private.firm_ids_for_tenant(_tenant_id) as f(firm_id)
    where app_private.has_firm_access(_user_id, f.firm_id)
       or app_private.platform_staff_can_access_firm(_user_id, f.firm_id)
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.has_tenant_access(_user_id uuid, _tenant_id text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.client_access ca
    JOIN public.client_xero_orgs cxo ON cxo.client_id = ca.client_id
    JOIN public.xero_connections xc ON xc.id = cxo.xero_connection_id
    WHERE ca.user_id = _user_id AND xc.tenant_id = _tenant_id
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.me_is_super_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'super_admin')
$function$
;
CREATE OR REPLACE FUNCTION app_private.user_can_read_client(_user_id uuid, _client_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT app_private.user_can_manage_client(_user_id, _client_id)
      OR app_private.has_client_access(_user_id, _client_id)
      OR EXISTS (
        SELECT 1 FROM public.clients c
        WHERE c.id = _client_id
          AND c.firm_id IS NOT NULL
          AND app_private.has_firm_access(_user_id, c.firm_id)
      )
$function$
;
CREATE OR REPLACE FUNCTION public.user_can_access_firm(_user_id uuid, _firm_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select _user_id is not null and _firm_id is not null
     and (app_private.has_firm_access(_user_id, _firm_id)
       or app_private.platform_staff_can_access_firm(_user_id, _firm_id))
$function$
;
CREATE OR REPLACE FUNCTION public.user_can_access_client(_user_id uuid, _client_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from public.clients c
    where c.id = _client_id
      and (public.user_can_access_firm(_user_id, c.firm_id)
        or app_private.has_client_access(_user_id, c.id))
  )
$function$
;
CREATE OR REPLACE FUNCTION app_private.is_org_owner(_user_id uuid, _firm_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (select 1 from public.firms f
                 where f.id = _firm_id and f.owner_user_id = _user_id)
      or app_private.is_firm_owner(_user_id, _firm_id)
$function$
;
CREATE OR REPLACE FUNCTION public.client_entitlement(_client_id uuid)
 RETURNS TABLE(tier dashboard_tier, source text, expires_at timestamp with time zone, in_grace boolean)
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'app_private'
AS $function$
DECLARE
  _uid uuid := auth.uid();
  _firm uuid;
  _always_free boolean := false;
  _sub public.client_subscriptions%ROWTYPE;
  _tier public.dashboard_tier := 'basic';
  _source text := 'none';
  _expires timestamptz := NULL;
  _grace boolean := false;
  _top public.dashboard_tier;
BEGIN
  IF _uid IS NULL OR NOT app_private.user_can_read_client(_uid, _client_id) THEN
    RETURN QUERY SELECT 'basic'::public.dashboard_tier, 'none'::text, NULL::timestamptz, false;
    RETURN;
  END IF;

  SELECT c.firm_id INTO _firm FROM public.clients c WHERE c.id = _client_id;
  IF _firm IS NOT NULL THEN
    SELECT f.is_always_free INTO _always_free FROM public.firms f WHERE f.id = _firm;
  END IF;

  -- Organisation lapsed: Standard only, whatever the client row says.
  IF _firm IS NOT NULL AND app_private.firm_subscription_lapsed(_firm) THEN
    RETURN QUERY SELECT 'basic'::public.dashboard_tier, 'org_lapsed'::text, NULL::timestamptz, false;
    RETURN;
  END IF;

  SELECT * INTO _sub FROM public.client_subscriptions s
   WHERE s.client_id = _client_id ORDER BY s.created_at DESC LIMIT 1;

  IF COALESCE(_always_free, false) THEN
    SELECT l.key::public.dashboard_tier INTO _top
    FROM public.plan_levels l
    LEFT JOIN public.tier_settings ts ON ts.tier = l.key
    WHERE l.scope='dashboard' AND l.enabled AND COALESCE(ts.enabled,true)
      AND l.key IN ('basic','advisory','investigate','multi_company')
    ORDER BY l.sort_order DESC LIMIT 1;
    _tier := COALESCE(_top,'basic'); _source := 'org_always_free';
  ELSIF _sub.id IS NOT NULL THEN
    IF _sub.subscription_type = 'free_forever' THEN
      _tier := COALESCE(_sub.dashboard_tier,'basic'); _source := 'free_forever';
    ELSIF _sub.subscription_type = 'trial' THEN
      IF _sub.trial_end IS NOT NULL AND _sub.trial_end > now() THEN
        _tier := _sub.dashboard_tier; _source := 'trial'; _expires := _sub.trial_end;
      END IF;
    ELSIF _sub.subscription_type = 'paid' THEN
      IF _sub.status IN ('active','trialing','free_forever') THEN
        _tier := _sub.dashboard_tier; _source := 'paid'; _expires := _sub.current_period_end;
      ELSIF _sub.status = 'past_due' AND _sub.current_period_end IS NOT NULL
            AND _sub.current_period_end > now() THEN
        _tier := _sub.dashboard_tier; _source := 'paid';
        _expires := _sub.current_period_end; _grace := true;
      END IF;
    END IF;
  END IF;

  IF _tier <> 'basic' AND EXISTS (
    SELECT 1 FROM public.tier_settings ts WHERE ts.tier = _tier::text AND ts.enabled = false
  ) THEN
    _tier := 'basic'; _source := 'none'; _expires := NULL; _grace := false;
  END IF;

  RETURN QUERY SELECT _tier, _source, _expires, _grace;
END;
$function$
;
CREATE OR REPLACE FUNCTION app_private.firm_limits(_firm_id uuid)
 RETURNS TABLE(client_limit integer, xero_org_limit integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select coalesce(s.client_limit_override, pl.client_limit), pl.xero_org_limit
  from public.subscriptions s
  left join public.plan_levels pl on pl.scope='firm' and pl.key = s.tier
  where s.firm_id = _firm_id
  limit 1
$function$
;
CREATE OR REPLACE FUNCTION public.client_allowed_widgets(_client_id uuid)
 RETURNS text[]
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  with ent as (select tier::text as tier from public.client_entitlement(_client_id)),
  fm as (select firm_id from public.clients where id = _client_id),
  ceiling as (
    select coalesce(pl.widgets,'{}'::text[])
        || case when public.firm_has_wip((select firm_id from fm))
                then coalesce((select w.widgets from public.plan_levels w
                                where w.scope='dashboard' and w.key='wip' and w.enabled),'{}'::text[])
                else '{}'::text[] end as w
    from ent left join public.plan_levels pl
      on pl.scope='dashboard' and pl.key = ent.tier and pl.enabled
  ),
  base as (
    select coalesce(
      (select twc.excluded_widgets from public.tier_widget_config twc
        where twc.client_id is null and twc.firm_id = (select firm_id from fm)
          and twc.tier = (select tier from ent)),
      (select twc.excluded_widgets from public.tier_widget_config twc
        where twc.client_id is null and twc.firm_id is null
          and twc.tier = (select tier from ent)),
      '{}'::text[]) as w
  ),
  excluded as (
    select (select b.w from base b)
        || coalesce((select twc.excluded_widgets from public.tier_widget_config twc
                      where twc.client_id = _client_id
                        and twc.tier = (select tier from ent)), '{}'::text[]) as w
  )
  select coalesce(array(
    select distinct x from unnest((select c.w from ceiling c)) as x
    except
    select e from unnest((select ex.w from excluded ex)) as e
  ),'{}'::text[])
$function$
;
CREATE OR REPLACE FUNCTION public.client_can_use_widget(_client_id uuid, _widget text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select _widget = any(public.client_allowed_widgets(_client_id))
$function$
;
CREATE OR REPLACE FUNCTION app_private.firm_subscription_lapsed(_firm_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select case
    -- Positive Traction's own organisation is never charged and never lapses.
    when exists (select 1 from public.firms f where f.id=_firm_id and f.is_always_free) then false
    else exists (
      select 1 from public.subscriptions s
      where s.firm_id = _firm_id
        and (
          (s.status = 'trialing' and s.trial_ends_at is not null and s.trial_ends_at < now())
          or s.status in ('canceled','unpaid','incomplete_expired')
          or (s.status = 'past_due' and s.current_period_end is not null
              and s.current_period_end < now())
        )
    )
  end
$function$
;
alter table public.reconciliation_snapshots enable row level security;
alter table public.client_access enable row level security;
alter table public.client_xero_orgs enable row level security;
alter table public.xero_connections enable row level security;
alter table public.user_roles enable row level security;
alter table public.consolidation_groups enable row level security;
alter table public.client_notes enable row level security;
alter table public.clients enable row level security;
alter table public.unreconciled_lines enable row level security;
alter table public.report_cache enable row level security;
alter table public.loan_consolidation_snapshots enable row level security;
alter table public.client_reports enable row level security;
alter table public.firm_support_access enable row level security;
alter table public.xero_oauth_states enable row level security;
alter table public.firm_members enable row level security;
alter table public.xero_snapshots enable row level security;
alter table public.firms enable row level security;
alter table public.client_subscriptions enable row level security;
alter table public.audit_log enable row level security;
alter table public.subscriptions enable row level security;
grant select on public.reconciliation_snapshots to authenticated;
grant select on public.client_access to authenticated;
grant select on public.client_xero_orgs to authenticated;
grant select on public.xero_connections to authenticated;
grant select on public.user_roles to authenticated;
grant select on public.consolidation_groups to authenticated;
grant select on public.client_notes to authenticated;
grant select on public.clients to authenticated;
grant select on public.unreconciled_lines to authenticated;
grant select on public.report_cache to authenticated;
grant select on public.loan_consolidation_snapshots to authenticated;
grant select on public.client_reports to authenticated;
grant select on public.firm_support_access to authenticated;
grant select on public.xero_oauth_states to authenticated;
grant select on public.firm_members to authenticated;
grant select on public.xero_snapshots to authenticated;
grant select on public.firms to authenticated;
grant select on public.client_subscriptions to authenticated;
grant select on public.audit_log to authenticated;
grant select on public.subscriptions to authenticated;
create policy "read reconciliation snapshots for accessible clients" on public.reconciliation_snapshots for select to authenticated using ((app_private.user_can_manage_client(auth.uid(), client_id) OR app_private.has_client_access(auth.uid(), client_id)));
create policy "manage client access by firm" on public.client_access for select to authenticated using (app_private.user_can_manage_client(auth.uid(), client_id));
create policy "viewers read own access" on public.client_access for select to authenticated using ((user_id = auth.uid()));
create policy "manage client xero orgs by firm" on public.client_xero_orgs for select to authenticated using (app_private.user_can_manage_client(auth.uid(), client_id));
create policy "viewers read assigned client xero orgs" on public.client_xero_orgs for select to authenticated using (app_private.has_client_access(auth.uid(), client_id));
create policy "Users manage own xero connections" on public.xero_connections for select to authenticated using ((auth.uid() = user_id));
create policy "firm members read firm xero connections" on public.xero_connections for select to authenticated using (((firm_id IS NOT NULL) AND app_private.has_firm_access(auth.uid(), firm_id)));
create policy "firm owners manage firm xero connections" on public.xero_connections for select to authenticated using (((firm_id IS NOT NULL) AND app_private.is_firm_owner(auth.uid(), firm_id)));
create policy "super admins manage roles" on public.user_roles for select to authenticated using (app_private.me_is_super_admin());
create policy "super admins read all roles" on public.user_roles for select to authenticated using (app_private.me_is_super_admin());
create policy "users read own roles" on public.user_roles for select to authenticated using ((user_id = auth.uid()));
create policy "Firm people can manage consolidation groups" on public.consolidation_groups for select to authenticated using (app_private.has_firm_access(auth.uid(), firm_id));
create policy "Firm people can view consolidation groups" on public.consolidation_groups for select to authenticated using ((app_private.has_firm_access(auth.uid(), firm_id) OR app_private.platform_staff_can_access_firm(auth.uid(), firm_id)));
create policy "Client viewers read notes" on public.client_notes for select to authenticated using (app_private.has_client_access(auth.uid(), client_id));
create policy "manage client notes by firm" on public.client_notes for select to authenticated using (app_private.user_can_manage_client(auth.uid(), client_id));
create policy "firm members read firm clients" on public.clients for select to authenticated using (((firm_id IS NOT NULL) AND app_private.has_firm_access(auth.uid(), firm_id)));
create policy "firm owners manage firm clients" on public.clients for select to authenticated using (((firm_id IS NOT NULL) AND app_private.is_firm_owner(auth.uid(), firm_id)));
create policy "viewers read assigned clients" on public.clients for select to authenticated using (app_private.has_client_access(auth.uid(), id));
create policy "Viewers can read lines for their client" on public.unreconciled_lines for select to authenticated using (app_private.has_client_access(auth.uid(), client_id));
create policy "manage unreconciled lines by firm" on public.unreconciled_lines for select to authenticated using (app_private.user_can_manage_client(auth.uid(), client_id));
create policy "Users manage own report cache" on public.report_cache for select to authenticated using ((auth.uid() = user_id));
create policy "Firm people can manage loan snapshots" on public.loan_consolidation_snapshots for select to authenticated using ((EXISTS ( SELECT 1
   FROM consolidation_groups g
  WHERE ((g.id = loan_consolidation_snapshots.group_id) AND app_private.has_firm_access(auth.uid(), g.firm_id)))));
create policy "Firm people can view loan snapshots" on public.loan_consolidation_snapshots for select to authenticated using ((EXISTS ( SELECT 1
   FROM consolidation_groups g
  WHERE ((g.id = loan_consolidation_snapshots.group_id) AND (app_private.has_firm_access(auth.uid(), g.firm_id) OR app_private.platform_staff_can_access_firm(auth.uid(), g.firm_id))))));
create policy "client viewers read their finalised reports" on public.client_reports for select to authenticated using ((app_private.has_client_access(auth.uid(), client_id) AND (status = ANY (ARRAY['final'::text, 'sent'::text]))));
create policy "staff read client reports" on public.client_reports for select to authenticated using (app_private.user_can_manage_client(auth.uid(), client_id));
create policy "Owners and members read support access" on public.firm_support_access for select to authenticated using ((app_private.is_super_admin(auth.uid()) OR app_private.has_firm_access(auth.uid(), firm_id) OR (EXISTS ( SELECT 1
   FROM firms f
  WHERE ((f.id = firm_support_access.firm_id) AND (f.owner_user_id = auth.uid()))))));
create policy "Users manage own oauth states" on public.xero_oauth_states for select to authenticated using ((auth.uid() = user_id));
create policy "firm members read own membership rows" on public.firm_members for select to authenticated using (((user_id = auth.uid()) OR app_private.has_firm_access(auth.uid(), firm_id)));
create policy "firm owners manage members" on public.firm_members for select to authenticated using (app_private.is_firm_owner(auth.uid(), firm_id));
create policy "super_admin reads memberships" on public.firm_members for select to authenticated using (app_private.is_super_admin(auth.uid()));
create policy "entitled users read client snapshots" on public.xero_snapshots for select to authenticated using ((user_can_access_client(auth.uid(), client_id) AND app_private.user_can_access_tenant(auth.uid(), tenant_id)));
create policy "firm members read own firm" on public.firms for select to authenticated using (app_private.has_firm_access(auth.uid(), id));
create policy "super_admin reads firms" on public.firms for select to authenticated using (app_private.is_super_admin(auth.uid()));
create policy "managers read client subscriptions" on public.client_subscriptions for select to authenticated using ((app_private.user_can_manage_client(auth.uid(), client_id) OR app_private.is_super_admin(auth.uid())));
create policy "staff manage client subscriptions" on public.client_subscriptions for select to authenticated using ((EXISTS ( SELECT 1
   FROM clients c
  WHERE ((c.id = client_subscriptions.client_id) AND app_private.platform_staff_can_access_firm(auth.uid(), c.firm_id)))));
create policy "super admins manage client subscriptions" on public.client_subscriptions for select to authenticated using (app_private.is_super_admin(auth.uid()));
create policy "super_admin reads audit" on public.audit_log for select to authenticated using (app_private.is_super_admin(auth.uid()));
create policy "firm members read own subscription" on public.subscriptions for select to authenticated using (app_private.has_firm_access(auth.uid(), firm_id));
create policy "super_admin reads subscriptions" on public.subscriptions for select to authenticated using (app_private.is_super_admin(auth.uid()));
