// Server-only: resolve who the caller is allowed to report on, and the client /
// organisation / Xero tenant the report is for.
//
// Invariants: the client id from the request is a FILTER (the grant comes from
// public.user_can_access_client); the tenant is resolved SERVER-SIDE from the
// client, never taken from the request; generating a report is an organisation
// staff action (public.user_can_access_firm), so an invited client viewer may
// read finalised reports but may not generate one.

export type ReportContext = {
  clientId: string;
  clientName: string;
  firmId: string;
  organisationName: string;
  tenantId: string;
  tenantName: string;
  currency: string;
};

export async function resolveReportContext(opts: {
  supabase: any;
  userId: string;
  clientId: string;
  /** Optional preference when a client has several Xero organisations. */
  preferTenantId?: string | null;
}): Promise<ReportContext> {
  const { assertClientDataAccessForClient, platformStaffCanAccessFirm } = await import(
    "@/lib/support-access.server"
  );
  await assertClientDataAccessForClient(opts.userId, opts.clientId);

  const { data: client, error } = await opts.supabase
    .from("clients")
    .select("id, name, firm_id, client_xero_orgs(xero_connections(tenant_id, tenant_name, status, base_currency))")
    .eq("id", opts.clientId)
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!client) throw new Error("Client not found.");
  const firmId = (client as any).firm_id as string | null;
  if (!firmId) throw new Error("This client is not attached to an organisation.");

  if (!(await platformStaffCanAccessFirm(opts.userId, firmId))) {
    throw new Error(
      "Management reports are generated by organisation members, or platform staff with an approved support grant.",
    );
  }

  const { data: firm } = await opts.supabase
    .from("firms")
    .select("name")
    .eq("id", firmId)
    .maybeSingle();

  const orgs = ((client as any).client_xero_orgs ?? [])
    .map((o: any) => o.xero_connections)
    .filter((c: any) => c?.tenant_id && c.status !== "disconnected");
  if (!orgs.length) {
    throw new Error("This client has no connected Xero organisation, so there is nothing to report on.");
  }
  const chosen =
    (opts.preferTenantId && orgs.find((o: any) => o.tenant_id === opts.preferTenantId)) || orgs[0];
  if (opts.preferTenantId && chosen.tenant_id !== opts.preferTenantId) {
    throw new Error("That Xero organisation is not linked to this client.");
  }

  return {
    clientId: opts.clientId,
    clientName: (client as any).name as string,
    firmId,
    organisationName: ((firm as any)?.name as string) ?? "Organisation",
    tenantId: chosen.tenant_id as string,
    tenantName: (chosen.tenant_name as string) ?? "Xero organisation",
    currency: (chosen.base_currency as string) ?? "AUD",
  };
}

/** Reports for this client, visible under the caller's own RLS. */
export async function listReportsForClient(supabase: any, clientId: string) {
  const { MONTHLY_REPORT_KEY } = await import("./monthly-report");
  const { data, error } = await supabase
    .from("client_reports")
    .select(
      "id, period_end, version, status, title, complete, payload_version, generated_at, generated_by, sent_at, finalised_at",
    )
    .eq("client_id", clientId)
    .eq("report_key", MONTHLY_REPORT_KEY)
    .order("period_end", { ascending: false })
    .order("version", { ascending: false });
  if (error) throw new Error(error.message);
  const ids = Array.from(new Set((data ?? []).map((r: any) => r.generated_by).filter(Boolean)));
  let names = new Map<string, string>();
  if (ids.length) {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: profiles } = await supabaseAdmin
      .from("profiles")
      .select("id, display_name, email")
      .in("id", ids as string[]);
    names = new Map((profiles ?? []).map((p: any) => [p.id, p.display_name ?? p.email ?? "Unknown"]));
  }
  return (data ?? []).map((r: any) => ({
    ...r,
    generated_by_name: r.generated_by ? (names.get(r.generated_by) ?? "Unknown") : "—",
  }));
}

/**
 * Persist a draft. `client_reports` has no write policy, so the write uses the
 * service role — AFTER access has been established by resolveReportContext.
 *
 * A `final` or `sent` report is never recomputed or overwritten: regenerating
 * creates the next version. A draft written by an older payload_version is
 * superseded and replaced in place.
 */
export async function saveDraftReport(opts: {
  ctx: ReportContext;
  userId: string;
  periodEnd: string;
  payload: any;
  payloadVersion: number;
  title: string;
}): Promise<{ id: string; version: number; supersededDraft: boolean }> {
  const { MONTHLY_REPORT_KEY } = await import("./monthly-report");
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

  const { data: existing, error } = await (supabaseAdmin as any)
    .from("client_reports")
    .select("id, version, status, payload_version")
    .eq("client_id", opts.ctx.clientId)
    .eq("report_key", MONTHLY_REPORT_KEY)
    .eq("period_end", opts.periodEnd)
    .order("version", { ascending: false });
  if (error) throw new Error(error.message);

  const rows = (existing ?? []) as any[];
  const latest = rows[0];
  const reusableDraft = latest && latest.status === "draft" ? latest : null;

  const row = {
    client_id: opts.ctx.clientId,
    firm_id: opts.ctx.firmId,
    tenant_id: opts.ctx.tenantId,
    report_key: MONTHLY_REPORT_KEY,
    period_end: opts.periodEnd,
    title: opts.title,
    payload: opts.payload,
    payload_version: opts.payloadVersion,
    status: "draft" as const,
    complete: !!opts.payload?.complete,
    generated_by: opts.userId,
    generated_at: new Date().toISOString(),
  };

  if (reusableDraft) {
    const { data, error: upErr } = await (supabaseAdmin as any)
      .from("client_reports")
      .update(row)
      .eq("id", reusableDraft.id)
      .select("id, version")
      .single();
    if (upErr) throw new Error(upErr.message);
    return {
      id: data.id,
      version: data.version,
      supersededDraft: Number(reusableDraft.payload_version ?? 0) < opts.payloadVersion,
    };
  }

  const nextVersion = (Number(latest?.version ?? 0) || 0) + 1;
  const { data, error: insErr } = await (supabaseAdmin as any)
    .from("client_reports")
    .insert({ ...row, version: nextVersion })
    .select("id, version")
    .single();
  if (insErr) throw new Error(insErr.message);

  const { writeAudit } = await import("@/lib/audit.server");
  await writeAudit({
    actorUserId: opts.userId,
    firmId: opts.ctx.firmId,
    action: "client_report_generated",
    targetType: "client",
    targetId: opts.ctx.clientId,
    meta: {
      report_key: MONTHLY_REPORT_KEY,
      period_end: opts.periodEnd,
      version: data.version,
      complete: row.complete,
    },
  }).catch(() => {});

  return { id: data.id, version: data.version, supersededDraft: false };
}
