/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsTiersRouteImport } from './routes/_authenticated/settings.tiers'
import { Route as AuthenticatedSettingsAdvisorsRouteImport } from './routes/_authenticated/settings.advisors'
import { Route as AuthenticatedSettingsActivityRouteImport } from './routes/_authenticated/settings.activity'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsClientIdIndexRouteImport } from './routes/_authenticated/clients.$clientId.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicXeroCallbackRouteImport } from './routes/api/public/xero/callback'
import { Route as AuthenticatedClientsClientIdUnreconciledRouteImport } from './routes/_authenticated/clients.$clientId.unreconciled'
import { Route as AuthenticatedClientsClientIdSettingsRouteImport } from './routes/_authenticated/clients.$clientId.settings'
import { Route as AuthenticatedClientsClientIdReceivablesTenantIdRouteImport } from './routes/_authenticated/clients.$clientId.receivables.$tenantId'
import { Route as AuthenticatedClientsClientIdPayablesTenantIdRouteImport } from './routes/_authenticated/clients.$clientId.payables.$tenantId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsTiersRoute =
  AuthenticatedSettingsTiersRouteImport.update({
    id: '/settings/tiers',
    path: '/settings/tiers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAdvisorsRoute =
  AuthenticatedSettingsAdvisorsRouteImport.update({
    id: '/settings/advisors',
    path: '/settings/advisors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsActivityRoute =
  AuthenticatedSettingsActivityRouteImport.update({
    id: '/settings/activity',
    path: '/settings/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsClientIdIndexRoute =
  AuthenticatedClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXeroCallbackRoute = ApiPublicXeroCallbackRouteImport.update({
  id: '/api/public/xero/callback',
  path: '/api/public/xero/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsClientIdUnreconciledRoute =
  AuthenticatedClientsClientIdUnreconciledRouteImport.update({
    id: '/clients/$clientId/unreconciled',
    path: '/clients/$clientId/unreconciled',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdSettingsRoute =
  AuthenticatedClientsClientIdSettingsRouteImport.update({
    id: '/clients/$clientId/settings',
    path: '/clients/$clientId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdReceivablesTenantIdRoute =
  AuthenticatedClientsClientIdReceivablesTenantIdRouteImport.update({
    id: '/clients/$clientId/receivables/$tenantId',
    path: '/clients/$clientId/receivables/$tenantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdPayablesTenantIdRoute =
  AuthenticatedClientsClientIdPayablesTenantIdRouteImport.update({
    id: '/clients/$clientId/payables/$tenantId',
    path: '/clients/$clientId/payables/$tenantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/advisors': typeof AuthenticatedSettingsAdvisorsRoute
  '/settings/tiers': typeof AuthenticatedSettingsTiersRoute
  '/clients/$clientId/settings': typeof AuthenticatedClientsClientIdSettingsRoute
  '/clients/$clientId/unreconciled': typeof AuthenticatedClientsClientIdUnreconciledRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
  '/clients/$clientId/payables/$tenantId': typeof AuthenticatedClientsClientIdPayablesTenantIdRoute
  '/clients/$clientId/receivables/$tenantId': typeof AuthenticatedClientsClientIdReceivablesTenantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/advisors': typeof AuthenticatedSettingsAdvisorsRoute
  '/settings/tiers': typeof AuthenticatedSettingsTiersRoute
  '/clients/$clientId/settings': typeof AuthenticatedClientsClientIdSettingsRoute
  '/clients/$clientId/unreconciled': typeof AuthenticatedClientsClientIdUnreconciledRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdIndexRoute
  '/clients/$clientId/payables/$tenantId': typeof AuthenticatedClientsClientIdPayablesTenantIdRoute
  '/clients/$clientId/receivables/$tenantId': typeof AuthenticatedClientsClientIdReceivablesTenantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/_authenticated/settings/advisors': typeof AuthenticatedSettingsAdvisorsRoute
  '/_authenticated/settings/tiers': typeof AuthenticatedSettingsTiersRoute
  '/_authenticated/clients/$clientId/settings': typeof AuthenticatedClientsClientIdSettingsRoute
  '/_authenticated/clients/$clientId/unreconciled': typeof AuthenticatedClientsClientIdUnreconciledRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
  '/_authenticated/clients/$clientId/payables/$tenantId': typeof AuthenticatedClientsClientIdPayablesTenantIdRoute
  '/_authenticated/clients/$clientId/receivables/$tenantId': typeof AuthenticatedClientsClientIdReceivablesTenantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/clients/new'
    | '/settings/activity'
    | '/settings/advisors'
    | '/settings/tiers'
    | '/clients/$clientId/settings'
    | '/clients/$clientId/unreconciled'
    | '/api/public/xero/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/clients/$clientId/'
    | '/clients/$clientId/payables/$tenantId'
    | '/clients/$clientId/receivables/$tenantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/clients/new'
    | '/settings/activity'
    | '/settings/advisors'
    | '/settings/tiers'
    | '/clients/$clientId/settings'
    | '/clients/$clientId/unreconciled'
    | '/api/public/xero/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/clients/$clientId'
    | '/clients/$clientId/payables/$tenantId'
    | '/clients/$clientId/receivables/$tenantId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/clients/new'
    | '/_authenticated/settings/activity'
    | '/_authenticated/settings/advisors'
    | '/_authenticated/settings/tiers'
    | '/_authenticated/clients/$clientId/settings'
    | '/_authenticated/clients/$clientId/unreconciled'
    | '/api/public/xero/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/clients/$clientId/'
    | '/_authenticated/clients/$clientId/payables/$tenantId'
    | '/_authenticated/clients/$clientId/receivables/$tenantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicXeroCallbackRoute: typeof ApiPublicXeroCallbackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/tiers': {
      id: '/_authenticated/settings/tiers'
      path: '/settings/tiers'
      fullPath: '/settings/tiers'
      preLoaderRoute: typeof AuthenticatedSettingsTiersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/advisors': {
      id: '/_authenticated/settings/advisors'
      path: '/settings/advisors'
      fullPath: '/settings/advisors'
      preLoaderRoute: typeof AuthenticatedSettingsAdvisorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/activity': {
      id: '/_authenticated/settings/activity'
      path: '/settings/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AuthenticatedSettingsActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId/': {
      id: '/_authenticated/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthenticatedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/xero/callback': {
      id: '/api/public/xero/callback'
      path: '/api/public/xero/callback'
      fullPath: '/api/public/xero/callback'
      preLoaderRoute: typeof ApiPublicXeroCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/$clientId/unreconciled': {
      id: '/_authenticated/clients/$clientId/unreconciled'
      path: '/clients/$clientId/unreconciled'
      fullPath: '/clients/$clientId/unreconciled'
      preLoaderRoute: typeof AuthenticatedClientsClientIdUnreconciledRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId/settings': {
      id: '/_authenticated/clients/$clientId/settings'
      path: '/clients/$clientId/settings'
      fullPath: '/clients/$clientId/settings'
      preLoaderRoute: typeof AuthenticatedClientsClientIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId/receivables/$tenantId': {
      id: '/_authenticated/clients/$clientId/receivables/$tenantId'
      path: '/clients/$clientId/receivables/$tenantId'
      fullPath: '/clients/$clientId/receivables/$tenantId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdReceivablesTenantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId/payables/$tenantId': {
      id: '/_authenticated/clients/$clientId/payables/$tenantId'
      path: '/clients/$clientId/payables/$tenantId'
      fullPath: '/clients/$clientId/payables/$tenantId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdPayablesTenantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedSettingsActivityRoute: typeof AuthenticatedSettingsActivityRoute
  AuthenticatedSettingsAdvisorsRoute: typeof AuthenticatedSettingsAdvisorsRoute
  AuthenticatedSettingsTiersRoute: typeof AuthenticatedSettingsTiersRoute
  AuthenticatedClientsClientIdSettingsRoute: typeof AuthenticatedClientsClientIdSettingsRoute
  AuthenticatedClientsClientIdUnreconciledRoute: typeof AuthenticatedClientsClientIdUnreconciledRoute
  AuthenticatedClientsClientIdIndexRoute: typeof AuthenticatedClientsClientIdIndexRoute
  AuthenticatedClientsClientIdPayablesTenantIdRoute: typeof AuthenticatedClientsClientIdPayablesTenantIdRoute
  AuthenticatedClientsClientIdReceivablesTenantIdRoute: typeof AuthenticatedClientsClientIdReceivablesTenantIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedSettingsActivityRoute: AuthenticatedSettingsActivityRoute,
  AuthenticatedSettingsAdvisorsRoute: AuthenticatedSettingsAdvisorsRoute,
  AuthenticatedSettingsTiersRoute: AuthenticatedSettingsTiersRoute,
  AuthenticatedClientsClientIdSettingsRoute:
    AuthenticatedClientsClientIdSettingsRoute,
  AuthenticatedClientsClientIdUnreconciledRoute:
    AuthenticatedClientsClientIdUnreconciledRoute,
  AuthenticatedClientsClientIdIndexRoute:
    AuthenticatedClientsClientIdIndexRoute,
  AuthenticatedClientsClientIdPayablesTenantIdRoute:
    AuthenticatedClientsClientIdPayablesTenantIdRoute,
  AuthenticatedClientsClientIdReceivablesTenantIdRoute:
    AuthenticatedClientsClientIdReceivablesTenantIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicXeroCallbackRoute: ApiPublicXeroCallbackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
