/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsTiersRouteImport } from './routes/_authenticated/settings.tiers'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsClientIdIndexRouteImport } from './routes/_authenticated/clients.$clientId.index'
import { Route as ApiPublicXeroCallbackRouteImport } from './routes/api/public/xero/callback'
import { Route as AuthenticatedClientsClientIdSettingsRouteImport } from './routes/_authenticated/clients.$clientId.settings'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsTiersRoute =
  AuthenticatedSettingsTiersRouteImport.update({
    id: '/settings/tiers',
    path: '/settings/tiers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsClientIdIndexRoute =
  AuthenticatedClientsClientIdIndexRouteImport.update({
    id: '/clients/$clientId/',
    path: '/clients/$clientId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicXeroCallbackRoute = ApiPublicXeroCallbackRouteImport.update({
  id: '/api/public/xero/callback',
  path: '/api/public/xero/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsClientIdSettingsRoute =
  AuthenticatedClientsClientIdSettingsRouteImport.update({
    id: '/clients/$clientId/settings',
    path: '/clients/$clientId/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/settings/tiers': typeof AuthenticatedSettingsTiersRoute
  '/clients/$clientId/settings': typeof AuthenticatedClientsClientIdSettingsRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
  '/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/settings/tiers': typeof AuthenticatedSettingsTiersRoute
  '/clients/$clientId/settings': typeof AuthenticatedClientsClientIdSettingsRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/settings/tiers': typeof AuthenticatedSettingsTiersRoute
  '/_authenticated/clients/$clientId/settings': typeof AuthenticatedClientsClientIdSettingsRoute
  '/api/public/xero/callback': typeof ApiPublicXeroCallbackRoute
  '/_authenticated/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/clients/new'
    | '/settings/tiers'
    | '/clients/$clientId/settings'
    | '/api/public/xero/callback'
    | '/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/clients/new'
    | '/settings/tiers'
    | '/clients/$clientId/settings'
    | '/api/public/xero/callback'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/clients/new'
    | '/_authenticated/settings/tiers'
    | '/_authenticated/clients/$clientId/settings'
    | '/api/public/xero/callback'
    | '/_authenticated/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicXeroCallbackRoute: typeof ApiPublicXeroCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/tiers': {
      id: '/_authenticated/settings/tiers'
      path: '/settings/tiers'
      fullPath: '/settings/tiers'
      preLoaderRoute: typeof AuthenticatedSettingsTiersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId/': {
      id: '/_authenticated/clients/$clientId/'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthenticatedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/xero/callback': {
      id: '/api/public/xero/callback'
      path: '/api/public/xero/callback'
      fullPath: '/api/public/xero/callback'
      preLoaderRoute: typeof ApiPublicXeroCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/$clientId/settings': {
      id: '/_authenticated/clients/$clientId/settings'
      path: '/clients/$clientId/settings'
      fullPath: '/clients/$clientId/settings'
      preLoaderRoute: typeof AuthenticatedClientsClientIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedSettingsTiersRoute: typeof AuthenticatedSettingsTiersRoute
  AuthenticatedClientsClientIdSettingsRoute: typeof AuthenticatedClientsClientIdSettingsRoute
  AuthenticatedClientsClientIdIndexRoute: typeof AuthenticatedClientsClientIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedSettingsTiersRoute: AuthenticatedSettingsTiersRoute,
  AuthenticatedClientsClientIdSettingsRoute:
    AuthenticatedClientsClientIdSettingsRoute,
  AuthenticatedClientsClientIdIndexRoute:
    AuthenticatedClientsClientIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicXeroCallbackRoute: ApiPublicXeroCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
