ALTER POLICY "firm owners manage invites" ON public.access_invites TO authenticated;
ALTER POLICY "super_admin reads invites" ON public.access_invites TO authenticated;
ALTER POLICY "super_admin reads audit" ON public.audit_log TO authenticated;
ALTER POLICY "firm members read own billing events" ON public.billing_events TO authenticated;
ALTER POLICY "super_admin reads billing events" ON public.billing_events TO authenticated;
ALTER POLICY "Manage cost classifications by firm (read)" ON public.client_cost_classifications TO authenticated;
ALTER POLICY "Viewers read cost classifications" ON public.client_cost_classifications TO authenticated;
ALTER POLICY "Client viewers read notes" ON public.client_notes TO authenticated;
ALTER POLICY "Manage true breakeven inputs by firm (read)" ON public.client_true_breakeven_inputs TO authenticated;
ALTER POLICY "Viewers read true breakeven inputs" ON public.client_true_breakeven_inputs TO authenticated;
ALTER POLICY "viewers read assigned client xero orgs" ON public.client_xero_orgs TO authenticated;
ALTER POLICY "firm members read firm clients" ON public.clients TO authenticated;
ALTER POLICY "firm owners manage firm clients" ON public.clients TO authenticated;
ALTER POLICY "viewers read assigned clients" ON public.clients TO authenticated;
ALTER POLICY "Users manage own dashboard configs" ON public.dashboard_configs TO authenticated;
ALTER POLICY "firm members read own membership rows" ON public.firm_members TO authenticated;
ALTER POLICY "firm owners manage members" ON public.firm_members TO authenticated;
ALTER POLICY "super_admin reads memberships" ON public.firm_members TO authenticated;
ALTER POLICY "Users view own profile" ON public.profiles TO authenticated;
ALTER POLICY "Users manage own report cache" ON public.report_cache TO authenticated;
ALTER POLICY "firm members read own subscription" ON public.subscriptions TO authenticated;
ALTER POLICY "super_admin reads subscriptions" ON public.subscriptions TO authenticated;
ALTER POLICY "Viewers can read lines for their client" ON public.unreconciled_lines TO authenticated;
ALTER POLICY "Viewers can update comments for their client" ON public.unreconciled_lines TO authenticated;
ALTER POLICY "Viewers can read uploads for their client" ON public.unreconciled_uploads TO authenticated;